"""
app.py - Flask application for the AI Road Damage Assessment System.

Routes:
    GET  /           → dashboard / upload page
    POST /analyze    → process uploaded image and return JSON results
    GET  /health     → API health check
"""

import os
import uuid
import json
import traceback
from pathlib import Path
from flask import Flask, render_template, request, jsonify
from werkzeug.utils import secure_filename
from dotenv import load_dotenv

from analyzer import RoadDamageAnalyzer
from ml_model import DamagePriorityModel
from report_generator import ReportGenerator, estimate_repair_cost

# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------
load_dotenv()

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024  # 16 MB max upload
app.config["UPLOAD_FOLDER"] = "uploads"
app.secret_key = os.getenv("FLASK_SECRET_KEY", "road-damage-secret-2024")

ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "webp", "bmp"}

# ------------------------------------------------------------------
# Module Initialization
# ------------------------------------------------------------------
os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)
os.makedirs("models", exist_ok=True)

analyzer = RoadDamageAnalyzer()

# Load ML model (trains on first run if needed)
priority_model = DamagePriorityModel()
try:
    priority_model.load()
    print("✓ ML model loaded successfully")
except FileNotFoundError:
    print("⚠ Model not found — training now (this may take a moment)…")
    import subprocess, sys
    subprocess.run([sys.executable, "ml_model.py"], check=True)
    priority_model.load()
    print("✓ ML model trained and loaded")

# Gemini report generator (optional — gracefully degrades if key missing)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
report_gen = None
if GEMINI_API_KEY:
    try:
        report_gen = ReportGenerator(GEMINI_API_KEY)
        print("✓ Gemini report generator ready")
    except Exception as e:
        print(f"⚠ Gemini init failed: {e}")
else:
    print("⚠ GEMINI_API_KEY not set — AI reports will use fallback text")


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def allowed_file(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def fallback_report(analysis: dict, priority: dict, cost: dict) -> str:
    """Returns a structured plain-text report when Gemini is unavailable."""
    p = priority["priority"]
    timeline_map = {
        "Low Priority": "12–24 months",
        "Medium Priority": "6–12 months",
        "High Priority": "1–3 months",
        "Critical Priority": "Within 1–2 weeks",
    }
    return f"""## Road Damage Inspection Report

### Executive Summary
The analysed road section shows **{analysis['damage_percentage']}%** surface damage with
**{analysis['num_damaged_regions']}** distinct damaged regions. The AI classification system
has rated this section as **{p}** with {priority['confidence']}% confidence.

### Detailed Damage Assessment
| Metric | Value |
|--------|-------|
| Damage Area | {analysis['damage_percentage']}% |
| Damaged Regions | {analysis['num_damaged_regions']} |
| Crack Density | {analysis['crack_density']} |
| Texture Roughness | {analysis['texture_roughness']} / 1.0 |
| Dark Surface | {analysis['dark_surface_percentage']}% |

### Risk Assessment
{"⛔ **CRITICAL RISK** – Immediate structural failure risk. Road may be unsafe for heavy vehicles." if p == "Critical Priority" else
 "🔴 **HIGH RISK** – Significant deterioration. Risk of accidents and rapid damage spread." if p == "High Priority" else
 "🟡 **MEDIUM RISK** – Moderate deterioration. Monitor closely and schedule repairs." if p == "Medium Priority" else
 "🟢 **LOW RISK** – Minor surface wear. Include in routine maintenance schedule."}

### Repair Recommendations
- Surface milling and resurfacing of damaged zones
- Crack sealing with bituminous compound
- Pothole patching using hot-mix asphalt
- Drainage inspection and remediation
- Reflective road marking renewal post-repair

### Suggested Repair Timeline
**{timeline_map.get(p, 'As scheduled')}**

### Cost Estimate
- Damaged Area: **{cost['damaged_area_m2']} m²**
- Rate: **₹{cost['cost_per_m2']}/m²**
- **Total Estimate: ₹{cost['estimated_cost']:,.2f} INR**

### Inspector Notes
This report is generated by an automated AI system. A qualified civil engineer
should conduct an on-site inspection before committing to a repair programme.
"""


# ------------------------------------------------------------------
# Routes
# ------------------------------------------------------------------

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/health")
def health():
    return jsonify({"status": "ok", "gemini": bool(report_gen)})


@app.route("/analyze", methods=["POST"])
def analyze():
    # --- Validate upload ---
    if "image" not in request.files:
        return jsonify({"error": "No image file provided"}), 400

    file = request.files["image"]
    if file.filename == "":
        return jsonify({"error": "No file selected"}), 400
    if not allowed_file(file.filename):
        return jsonify({"error": "Invalid file type. Use PNG, JPG, JPEG, WEBP, or BMP"}), 400

    # --- Save upload ---
    ext = Path(secure_filename(file.filename)).suffix
    unique_name = f"{uuid.uuid4().hex}{ext}"
    save_path = os.path.join(app.config["UPLOAD_FOLDER"], unique_name)
    file.save(save_path)

    try:
        # 1. OpenCV feature extraction
        analysis = analyzer.extract_features(save_path)

        # 2. ML priority prediction
        priority_result = priority_model.predict({
            "damage_percentage": analysis["damage_percentage"],
            "num_damaged_regions": analysis["num_damaged_regions"],
            "crack_density": analysis["crack_density"],
            "texture_roughness": analysis["texture_roughness"],
            "dark_surface_percentage": analysis["dark_surface_percentage"],
        })

        # 3. Cost estimation
        cost_result = estimate_repair_cost(
            damage_percentage=analysis["damage_percentage"],
            priority=priority_result["priority"],
            num_damaged_regions=analysis["num_damaged_regions"],
        )

        # 4. AI report (Gemini or fallback)
        if report_gen:
            try:
                report_md = report_gen.generate(analysis, priority_result, cost_result)
            except Exception as e:
                print(f"Gemini error: {e}")
                report_md = fallback_report(analysis, priority_result, cost_result)
        else:
            report_md = fallback_report(analysis, priority_result, cost_result)

        return jsonify({
            "success": True,
            "analysis": {
                "damage_percentage": analysis["damage_percentage"],
                "num_damaged_regions": analysis["num_damaged_regions"],
                "crack_density": analysis["crack_density"],
                "texture_roughness": analysis["texture_roughness"],
                "dark_surface_percentage": analysis["dark_surface_percentage"],
            },
            "priority": priority_result,
            "cost": cost_result,
            "report": report_md,
            "original_image": f"data:image/jpeg;base64,{analysis['original_image_b64']}",
            "processed_image": f"data:image/jpeg;base64,{analysis['processed_image_b64']}",
        })

    except Exception:
        traceback.print_exc()
        return jsonify({"error": "Analysis failed. Please try a different image."}), 500

    finally:
        # Clean up uploaded file
        try:
            os.remove(save_path)
        except Exception:
            pass


# ------------------------------------------------------------------
# Entry point
# ------------------------------------------------------------------
if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    debug = os.getenv("FLASK_DEBUG", "true").lower() == "true"
    print(f"\n🚀 Road Damage Assessment System running on http://localhost:{port}\n")
    app.run(host="0.0.0.0", port=port, debug=debug)
